[workspace]
members = [
    "hello_cargo",
    "hello_world",
    "guessing_game", "contact_fomular",
]
resolver = "2"

[package]
name = "LearnRust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0"
